import type { Metadata } from "next";

import "./globals.css";

import { Mona_Sans } from "next/font/google";

import Nav from "@/components/Nav";

const monaSans = Mona_Sans({
  subsets: ["latin"],
  variable: "--font-mona-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Nav />
      <body className={`${monaSans.variable} font-sans`}>
        <Nav />
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
